# Generated by Django 2.2 on 2021-06-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mansimehndiratta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
