# Generated by Django 2.2 on 2021-06-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mansimehndiratta', '0002_auto_20210624_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('writer', models.CharField(max_length=122)),
                ('read_time', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=100000)),
            ],
        ),
    ]
