# Generated by Django 2.2 on 2021-06-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mansimehndiratta', '0003_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='title',
            field=models.CharField(default='generic', max_length=1000),
            preserve_default=False,
        ),
    ]
