# Generated by Django 2.2 on 2021-06-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mansimehndiratta', '0004_blogs_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='pdf',
            field=models.FileField(default='none', upload_to='pdf'),
            preserve_default=False,
        ),
    ]
