# Generated by Django 2.2 on 2021-06-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mansimehndiratta', '0005_blogs_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='title_image',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
