# Generated by Django 2.2 on 2021-06-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mansimehndiratta', '0006_blogs_title_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='pdf',
        ),
    ]
